baseURL = "https://pth-in.github.io/polemics"
languageCode = "en-us"
title = "Polemics"
theme = "paper"

[params]
  description = "Critical analysis of historical and scientific claims"
  author = "Polemics"
  color = "linen"
  twitter = "pth77873528"
  github = "pth-in"
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

